services:

  discuss:
    build: .
    volumes:
      - $PWD:/discuss
    tty: true
    stdin_open: true
    ports:
      - 4000:4000
    
  postgres:    
    image: postgres:latest
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  admin:
    image: adminer
    depends_on: 
      - postgres
    ports:
      - 8080:8080
volumes:
  pgdata:
